In [1]:
import numpy as np
def broadcast_ops(X: np.ndarray, b: np.ndarray, w: np.ndarray) -> np.ndarray:
    
  """
La función lo que hará es sumar un vector fila y se aplica en cada fila de la 
matriz de manera que a la primera entrada del vector que se suma se aplica en la
primera entrada de la fila y así sucesivamente con todas las filas y después de 
ese resultado, se va a multiplicar un vector columna que la primera entrada del 
vector columna va a multiplicar la primera entrada de todas las columnas y así 
sucesivamente con todas las entradas de las columnas.

Variables
----------
X: es la matriz a modificar de dimensión (N,D)
b: es un vector que se sumará entrada por entrada de tamaño (D,)
w: es un vector que se va a multiplicar entrada por entrada de dimensión (W,)
Retorna
---------- 
Y = (X+b)*w 
  """
# hay que modificar el w para que tenga sentido 
  Y = (X + b) * w[:,None]

  return Y

In [2]:
import numpy as np
def matmul_naive(A: np.ndarray, B: np.ndarray) -> np.ndarray:
  """
  La función va a resolver la multiplicación de matrices de una forma clásica
  es decir a través de que  se define la entrada Cij como la suma de los 
  productos de la entrada ik de la matriz A por la entrada kj de la matriz B
  sobre todos los k y así se tiene iterar para cada i y para cada j.
  Entonces vamos a hacer tres ciclos uno para mover el índice i otro para el 
  índice j y el último para que haga lo anteriormente descrito de la entrada Cij
  
  Variables
  ----------
  A: una matriz de tamaño N x M
  B: una matriz de tamaño R x S

  Retorna
  ----------
  C: La matriz resultante de hacer el producto matricial de A con B
  """
  # Verificar el tamaño de las matrices

  # Cantidad de filas de la matriz A
  rowA = A.shape[0]
  
  # Cantidad de columnas de la matriz A
  colA= A.shape[1]  
  
  # Cantidad de filas de la matriz B 
  rowB= B.shape[0]

  # Cantidad de columnas de la matriz B
  colB = B.shape[1]

  if colA == rowB:

  # Se crea la matriz C
    C = np.zeros((rowA,colB))

    # Iteramos sobre cada fila de A
    for i in range(rowA):
      # Itermaos sobre la cantidad de columnas de B
        for j in range(colB):
           # Iteramos para los k i.e. donde colA = rowB
            for k in range(colA):
              C[i,j] += A[i,k]* B[k,j]

    return C
  else:
     print("No se puede multiplicar estas matrices")

In [3]:
import numpy as np
def matmul_vectorized(A: np.ndarray, B: np.ndarray) -> np.ndarray:
  """
  En numpy hay unas operaciones que hacen ese trabajo sucio que hicimos antes
  en un símbolo entonces vamos a establecerla

 Variables
 ----------
 A: una matriz de tamaño N x M
 B: una matriz de tamaño R x S

 Retorna
 ----------
  C: La matriz resultante de hacer el producto matricial de A con B
  """
  C = A @ B
  return C

In [4]:
import numpy as np

def elementwise_ops(a: np.ndarray, b: np.ndarray) -> dict[str, np.ndarray]:
  """
  Tenemos que aplicar en un diccionario las operaciones de suma, multiplicación 
  y división entrada por entrada de los tensores y en el caso de la división se
  trabaja con la entrada más un epsilon muy pequeño.

  """

# Definimos el epsilon
  epsilon = 1e-8
# Definimos el diccionario

  respuesta = {}
  respuesta["add"] = a + b
  respuesta["mul"] = a * b
  respuesta["div"] = a / b

  return respuesta


In [6]:
import numpy as np
def reshape_and_transpose(x, B, C, H, W):
    """
    Convierte un vector 1D de imágenes desde formato aplanado
    al formato NHWC.

    Primero organiza los datos como NCHW: (B, C, H, W).
    Luego transpone los ejes para obtener NHWC: (B, H, W, C).

    Parámetros:
        x: vector 1D con B*C*H*W elementos.
        B: cantidad de imágenes del lote.
        C: cantidad de canales.
        H: altura de cada imagen.
        W: ancho de cada imagen.

    Retorna:
        np.ndarray con forma (B, H, W, C).
    """
    # 1. Verificar tamaño correcto
    if len(x) != B * C * H * W:
        raise ValueError("El tamaño de x no coincide con B*C*H*W")

    # 2. Convertir a arreglo NumPy
    x = np.array(x)

    # 3. Remodelar a formato NCHW: (B, C, H, W)
    tensor_nchw = x.reshape(B, C, H, W)

    # 4. Transponer a formato NHWC: (B, H, W, C)
    tensor_nhwc = np.transpose(tensor_nchw, (0, 2, 3, 1))

    return tensor_nhwc

    
#Prueba

x = list(range(1, 25))
B = 1
C = 2
H = 3
W = 4

resultado = reshape_and_transpose(x, B, C, H, W)

print(resultado)
print("Forma final:", resultado.shape)

[[[[ 1 13]
   [ 2 14]
   [ 3 15]
   [ 4 16]]

  [[ 5 17]
   [ 6 18]
   [ 7 19]
   [ 8 20]]

  [[ 9 21]
   [10 22]
   [11 23]
   [12 24]]]]
Forma final: (1, 3, 4, 2)


Primero se verifica que el tamaño del vector sea B * C * H * W, porque esa es la cantidad total de datos necesarios para construir el tensor de imágenes. Si el vector tiene más o menos elementos, no se puede reorganizar correctamente.

Luego se aplica reshape(B, C, H, W). Esta operación no cambia los valores del vector, solo cambia la forma en que se agrupan. El resultado queda en formato NCHW, donde B representa el lote, C los canales, H la altura y W el ancho.

Después se utiliza transpose(tensor_nchw, (0, 2, 3, 1)). Esto cambia el orden de las dimensiones. La dimensión 0, que es B, queda igual. La dimensión 2, que es H, pasa al segundo lugar. La dimensión 3, que es W, pasa al tercer lugar. La dimensión 1, que es C, pasa al último lugar.

Por eso la forma cambia de:

(B, C, H, W)

a:

(B, H, W, C)

En conclusión, reshape organiza el vector como un tensor de cuatro dimensiones y transpose cambia el orden de los ejes. Los datos no se modifican; solamente se reorganiza su estructura.

In [7]:
import numpy as np

def tensor_reductions(x, axis):
    """
    Aplica operaciones de reducción sobre un tensor.

    Calcula suma, media, máximo y argmax a lo largo de un eje específico.

    Parámetros:
        x: lista o arreglo con datos del tensor.
        axis: eje sobre el cual se aplican las reducciones.
              Puede ser un entero o None.

    Retorna:
        dict con las siguientes claves:
            "sum": suma de los elementos
            "mean": promedio de los elementos
            "max": valor máximo
            "argmax": índice del valor máximo
    """

    # 1. Convertir la entrada a arreglo NumPy
    tensor = np.array(x)

    # 2. Calcular la suma a lo largo del eje
    suma = np.sum(tensor, axis=axis)

    # 3. Calcular la media (promedio)
    media = np.mean(tensor, axis=axis)

    # 4. Encontrar el valor máximo
    maximo = np.max(tensor, axis=axis)

    # 5. Encontrar el índice del valor máximo
    indice_maximo = np.argmax(tensor, axis=axis)

    # 6. Guardar resultados en un diccionario
    resultados = {
        "sum": suma,
        "mean": media,
        "max": maximo,
        "argmax": indice_maximo
    }

    return resultados


# Prueba

x = [[1, 2, 3],
     [4, 5, 6]]

axis = 1

resultado = tensor_reductions(x, axis)

print("Suma:", resultado["sum"])
print("Media:", resultado["mean"])
print("Máximo:", resultado["max"])
print("Argmax:", resultado["argmax"])

Suma: [ 6 15]
Media: [2. 5.]
Máximo: [3 6]
Argmax: [2 2]


Las operaciones de reducción permiten resumir la información de un tensor a lo largo de una dimensión específica.

El parámetro axis indica sobre qué eje se realiza la operación. Por ejemplo, si axis=1, se reduce cada fila, es decir, se combinan los valores de cada fila en un solo resultado.

Desde el punto de vista matemático:

- La suma calcula:
  sum = x₁ + x₂ + ... + xₙ

- La media calcula:
  mean = (1/n) * (x₁ + x₂ + ... + xₙ)

- El máximo selecciona el valor más grande del conjunto:
  max = max(x₁, x₂, ..., xₙ)

- El argmax devuelve la posición donde ocurre ese valor máximo.

Cuando se aplica una reducción, la dimensión correspondiente al eje se elimina. Por ejemplo, si el tensor tiene forma (2, 3) y se reduce en axis=1, el resultado tendrá forma (2,), ya que cada fila se convierte en un solo valor.

Estas operaciones no modifican los datos originales, sino que generan un resumen de menor dimensión, lo cual es fundamental en aprendizaje profundo para calcular pérdidas, estadísticas y decisiones de clasificación.


In [12]:
import numpy as np

def cross_entropy_loss(probs, targets):
    """
    Calcula la pérdida de entropía cruzada promedio.

    Parámetros:
        probs: matriz (N, C) con probabilidades.
        targets: vector (N,) con índices de la clase correcta.

    Retorna:
        float: pérdida promedio.
    """

    # 1. Convertir entradas a arreglos NumPy
    probs = np.array(probs)
    targets = np.array(targets)

    # 2. Obtener tamaño del lote
    N = probs.shape[0]

    # 3. Definir épsilon para evitar log(0)
    eps = 1e-9

    # 4. Guardar las probabilidades correctas
    correct_probs = []

    # 5. Recorrer cada muestra y tomar la probabilidad de la clase correcta
    for i in range(N):
        correct_probs.append(probs[i][targets[i]])

    # 6. Convertir la lista a arreglo NumPy
    correct_probs = np.array(correct_probs)

    # 7. Calcular la pérdida promedio
    loss = -np.mean(np.log(correct_probs + eps))

    # 8. Convertir a float normal de Python
    return float(loss)

# Prueba

probs = [[0.1, 0.9],
         [0.8, 0.2]]

targets = [1, 0]

resultado = cross_entropy_loss(probs, targets)

print("Pérdida:", resultado)

Pérdida: 0.16425203230546248


La pérdida de entropía cruzada mide qué tan bien las probabilidades predichas por el modelo coinciden con la clase verdadera.

Primero, se tiene una matriz probs donde cada fila representa una distribución de probabilidad sobre las clases. Además, se tiene un vector targets que indica cuál es la clase correcta para cada muestra.

Para cada muestra i, se toma la probabilidad que el modelo asigna a la clase correcta, es decir:

p(i, y_i)

Esto se obtiene recorriendo cada fila del arreglo y seleccionando la posición correspondiente a la clase correcta usando un ciclo for.

Luego se aplica el logaritmo negativo:

-log(p(i, y_i))

Esto mide el error de la predicción:
- Si la probabilidad es alta (cerca de 1), la pérdida es pequeña.
- Si la probabilidad es baja (cerca de 0), la pérdida es grande.

Después, se promedian todas las pérdidas:

loss = -(1/N) * sum(log(p(i, y_i)))

donde N es la cantidad de muestras.

Se utiliza un pequeño valor epsilon (1e-9) para evitar problemas cuando la probabilidad es 0, ya que log(0) no está definido.

Finalmente, se devuelve un solo número que representa la pérdida promedio del modelo. Un valor pequeño indica buenas predicciones, mientras que un valor grande indica que el modelo está cometiendo errores.

In [2]:
import numpy as np
from typing import Tuple

def grad_sum(grad_y: float, x_shape: Tuple[int]) -> np.ndarray:
    """
    Dada la función y = sum(x), donde x es un vector,
    la derivada parcial de y respecto a x_i es 1 para cada i.
    Ahora, ∂L/∂x_i = (∂L/∂y)(∂y/∂x_i) = grad_y ⋅ 1 = grad_y.
    Esto quiere decir que cada entrada del vector grad_x es grad_y.
    
    Argumentos:
        grad_y: Gradiente escalar dL/dy
        x_shape: Forma del tensor x
        
    Retorna:
        Gradiente dL/dx con forma x_shape
    """
    return np.full(x_shape, grad_y)